import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cls } from '@/lib/client/utils';
import SWRProvider from '@/components/SWRProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Maeil-Tweet',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cls(inter.className, 'w-full max-w-lg mx-auto')}>
        <SWRProvider>{children}</SWRProvider>
      </body>
    </html>
  );
}
