import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cls } from '@/lib/client/utils';
import SWRProvider from '@/components/SWRProvider';
import { cookies } from 'next/headers';
import { getThemeName } from '@/lib/common/theme';
import { ThemeMode } from '@/lib/types';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Maeil-Tweet',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const theme = cookieStore.get('theme');
  const themeName = getThemeName(theme?.value as ThemeMode);

  return (
    <html lang="en" data-theme={themeName}>
      <body className={cls(inter.className, 'w-full max-w-lg mx-auto')}>
        <SWRProvider>{children}</SWRProvider>
      </body>
    </html>
  );
}
